language: objective-c

branches:
 only:
 - master

xcode_project: WeekCount.xcodeproj
xcode_scheme: WeekCount
osx_image: xcode7.3

script:
- xcodebuild clean build test -project WeekCount.xcodeproj -scheme WeekCount
